# Generated by Django 4.2 on 2025-12-31 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_account_number_member_bank_name'),
        ('expenses', '0002_expense_created_by'),
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUpdateOffset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.BigIntegerField(default=0, help_text='Last processed Telegram update_id')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'telegram_update_offset',
            },
        ),
        migrations.CreateModel(
            name='PaymentConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount being confirmed', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', help_text='Current status of confirmation request', max_length=20)),
                ('confirmation_message_id', models.CharField(blank=True, help_text='Telegram message ID for editing confirmation message', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Timestamp when confirmation was completed', null=True)),
                ('debtor', models.ForeignKey(help_text='Member who owes money', on_delete=django.db.models.deletion.CASCADE, related_name='payment_confirmations_as_debtor', to='members.member')),
                ('expense_participants', models.ManyToManyField(help_text='Expense participants being settled', related_name='payment_confirmations', to='expenses.expenseparticipant')),
                ('initiated_by', models.ForeignKey(help_text='Member who initiated the confirmation request', on_delete=django.db.models.deletion.CASCADE, related_name='initiated_payment_confirmations', to='members.member')),
                ('lender', models.ForeignKey(help_text='Member who receives payment', on_delete=django.db.models.deletion.CASCADE, related_name='payment_confirmations_as_lender', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentconfirmation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('debtor', 'lender', 'status'), name='unique_pending_confirmation_per_pair'),
        ),
    ]
